rss:
  - name: BBC Vietnamese
    url: "https://www.bbc.co.uk/vietnamese/index.xml"
  - name: Cafebiz - Tài chính
    url: "http://cafebiz.vn/tai-chinh.rss"
  - name: Cafebiz - Chính sách
    url: "http://cafebiz.vn/chinh-sach.rss"
  - name: corey.tech
    url: "https://corey.tech/feed.xml"
  - name: SRE Weekly
    url: "http://sreweekly.com/feed/"
  - name: StatusCode Weekly
    url: "https://weekly.statuscode.com/rss/"
  - name: Grokking Newsletter
    url: "http://newsletter.grokking.org/?format=rss"
