rss:
  - name: BBC Vietnamese
    url: "https://www.bbc.co.uk/vietnamese/index.xml"
  - name: Cafebiz - Tài chính
    url: "http://cafebiz.vn/tai-chinh.rss"
  - name: Cafebiz - Chính sách
    url: "http://cafebiz.vn/chinh-sach.rss"
  - name: Cafebiz - Kinh doanh
    url: "http://cafebiz.vn/cau-chuyen-kinh-doanh.rss"
  - name: Cafebiz - Pháp luật
    url: "http://cafebiz.vn/phap-luat.rss"
