rss:
  - name: BBC Vietnamese
    url: "https://www.bbc.co.uk/vietnamese/index.xml"
  - name: Cafebiz - Tài chính
    url: "http://cafebiz.vn/tai-chinh.rss"
  - name: Cafebiz - Chính sách
    url: "http://cafebiz.vn/chinh-sach.rss"
